name: Unit tests for asaman
on: [pull_request]
jobs:
  Run-Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create virtualenv and install the dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install -r dev-requirements.txt
      - name: Run the tests
        run: |
          source .venv/bin/activate
          pytest -vvv
      - run: echo "🍏 This job's status is ${{ job.status }}."
